import { useState, useCallback, useEffect } from 'react';
import { Platform } from 'react-native';
import { GoogleSignin, isErrorWithCode, statusCodes } from '@react-native-google-signin/google-signin';
import { GoogleAuthProvider, signInWithPopup } from 'firebase/auth';
import { authApi } from '../api/auth';
import { usersApi } from '../api/users';
import { secureStorage } from '../utils/secureStorage';
import { useAuthStore, useGemsStore } from '../store';
import { getApiErrorMessage, isNetworkError, getNetworkErrorMessage } from '../utils/errorMessages';
import { firebaseAuth, auth } from '../config/firebase';

// Google OAuth web client ID for identifying the backend environment
const GOOGLE_WEB_CLIENT_ID = process.env.EXPO_PUBLIC_GOOGLE_WEB_CLIENT_ID || '';

interface UseGoogleAuthResult {
    signInWithGoogle: () => Promise<void>;
    loading: boolean;
    error: string | null;
}

export const useGoogleAuth = (): UseGoogleAuthResult => {
    const { setAuth } = useAuthStore();
    const { syncFromUser } = useGemsStore();
    const [loading, setLoading] = useState(false);
    const [error, setError] = useState<string | null>(null);

    // Ensure Google Sign-In is configured on mount for Native
    useEffect(() => {
        if (Platform.OS !== 'web') {
            GoogleSignin.configure({
                webClientId: GOOGLE_WEB_CLIENT_ID,
                offlineAccess: false,
            });
        }
    }, []);

    const signInWithGoogle = useCallback(async () => {
        setLoading(true);
        setError(null);

        try {
            let firebaseIdToken: string | null = null;

            if (Platform.OS === 'web') {
                // --- WEB FLOW ---
                // Native libraries like Google Play Services don't exist on the web. 
                // We use standard Firebase Web Auth popups instead.
                const provider = new GoogleAuthProvider();
                const result = await signInWithPopup(auth, provider);
                // After successful web login, grab the secure Firebase session token
                firebaseIdToken = await result.user.getIdToken();
                
                if (!firebaseIdToken) {
                    throw new Error('Failed to generate secure Firebase session token on web.');
                }
            } else {
                // --- NATIVE (iOS/Android) FLOW ---
                // Initiate the native Google Sign-In OS prompt
                await GoogleSignin.hasPlayServices();
                const userInfo = await GoogleSignin.signIn();

                // Extract native Google ID token
                const idToken = userInfo.data?.idToken;

                if (!idToken) {
                    throw new Error('No ID token obtained from Google Sign-In');
                }

                // Authenticate with Firebase locally on the mobile client
                await firebaseAuth.signInWithGoogle(idToken);

                // Fetch a fresh unified Firebase Session token
                firebaseIdToken = await firebaseAuth.getIdToken();
                
                if (!firebaseIdToken) {
                    throw new Error("Failed to generate secure Firebase session token.");
                }
            }

            // Synchronize unified session token with our robust backend router
            const authResponse = await authApi.sync(firebaseIdToken);

            // Store custom JWT tokens generated by MongoDB backend
            await secureStorage.setItemAsync('accessToken', authResponse.tokens.accessToken);
            await secureStorage.setItemAsync('refreshToken', authResponse.tokens.refreshToken);

            // Load complete DB profile
            const userProfile = await usersApi.getMe();

            // Store unified auth profile locally in Zustand global state
            await setAuth(
                userProfile,
                authResponse.tokens.accessToken,
                authResponse.tokens.refreshToken
            );

            // Sync app state elements like Gems
            syncFromUser(userProfile);

            setError(null);
        } catch (err: any) {
            // Handle Native-Specific Errors
            if (Platform.OS !== 'web' && isErrorWithCode(err)) {
                switch (err.code) {
                    case statusCodes.SIGN_IN_CANCELLED:
                        // User gently tapped out
                        setError(null); 
                        break;
                    case statusCodes.IN_PROGRESS:
                        setError('Sign in is already in progress');
                        break;
                    case statusCodes.PLAY_SERVICES_NOT_AVAILABLE:
                        setError('Google Play Services is not available or outdated.');
                        break;
                    default:
                        setError('Google Sign-In failed. ' + (err.message || ''));
                }
            // Handle Web-Specific Firebase Auth popup errors
            } else if (err.code === 'auth/popup-closed-by-user') {
                setError(null); // User closed popup
            } else if (isNetworkError(err)) {
                setError(getNetworkErrorMessage(err));
            } else if (err.response?.status === 409 && err.response?.data?.error === 'AUTH_PROVIDER_CONFLICT') {
                setError(err.response.data.message || 'This email is already registered with a different sign-in method.');
            } else {
                setError(getApiErrorMessage(err) || 'An unexpected error occurred during Google Sign-In.');
            }
        } finally {
            setLoading(false);
        }
    }, [setAuth, syncFromUser]);

    return {
        signInWithGoogle,
        loading,
        error,
    };
};

export default useGoogleAuth;
